helmfiles:
- ngrok.helmfile.yaml

repositories:
- name: brigade
  url: https://brigadecore.github.io/charts

releases:
- name: brigade
  chart: brigade/brigade
  values:
  - brigade-github-app:
      enabled: false
    rbac:
      enabled: true
    registry: brigadecore
    name: brigade-github-app
    github:
      key: |
{{ readFile (requiredEnv "BRIGADE_GITHUB_APP_KEY") | indent 8 }}
    checkSuiteOnPR: true
    appID: {{ requiredEnv "BRIGADE_GITHUB_APP_ID" }}
- name: brigade-github-app
  chart: brigade/brigade-github-app
  values:
  - rbac:
      enabled: true
    sharedSecret: {{ requiredEnv "BRIGADE_PROJECT_SECRET" }}
    github:
      key: |
{{ readFile (requiredEnv "BRIGADE_GITHUB_APP_KEY") | indent 8 }}
- name: project
  chart: brigade/brigade-project
  values:
  - project: "mumoshu/helmfile-gitops"
    repository: "github.com/mumoshu/helmfile-gitops"
    cloneURL: "git@github.com:mumoshu/helmfile-gitops.git"
    secrets: {}
    github:
      token: {{ requiredEnv "GITHUB_TOKEN" }}
    sharedSecret: {{ requiredEnv "BRIGADE_PROJECT_SECRET" }}
    defaultScript: |
      const { events, Job } = require("brigadier")
      function run(e, project) {
        console.log("hello default script")
      }
      events.on("run", run)
    sshKey:
{{ readFile (requiredEnv "SSH_KEY") | indent 6 }}
